services:
  - type: web
    name: ytmp3
    env: node
    buildCommand: "npm install && pip install -U yt-dlp"
    startCommand: "node server.js"
    envVars:
      - key: NODE_VERSION
        value: 18
